import 'package:flutter/material.dart';

import '../tokens/app_colors.dart';

const ColorScheme studentColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: AppColors.studentPrimary,
  onPrimary: AppColors.onPrimary,
  primaryContainer: AppColors.primaryContainer,
  onPrimaryContainer: AppColors.onPrimaryContainer,
  secondary: AppColors.secondary,
  onSecondary: AppColors.onSecondary,
  secondaryContainer: AppColors.secondaryContainer,
  onSecondaryContainer: AppColors.onSecondaryContainer,
  tertiary: AppColors.tertiary,
  onTertiary: AppColors.onTertiary,
  tertiaryContainer: AppColors.tertiaryContainer,
  onTertiaryContainer: AppColors.onTertiaryContainer,
  error: AppColors.error,
  onError: AppColors.onError,
  errorContainer: AppColors.errorContainer,
  onErrorContainer: AppColors.onErrorContainer,
  surface: AppColors.surface,
  onSurface: AppColors.onSurface,
  onSurfaceVariant: AppColors.onSurfaceVariant,
  surfaceContainerLowest: AppColors.surfaceContainerLowest,
  surfaceContainerLow: AppColors.surfaceContainerLow,
  surfaceContainer: AppColors.surfaceContainer,
  surfaceContainerHigh: AppColors.surfaceContainerHigh,
  surfaceContainerHighest: AppColors.surfaceContainerHighest,
  surfaceDim: AppColors.surfaceDim,
  surfaceBright: AppColors.surfaceBright,
  surfaceTint: AppColors.studentPrimary,
  outline: AppColors.outline,
  outlineVariant: AppColors.outlineVariant,
  inverseSurface: AppColors.inverseSurface,
  onInverseSurface: AppColors.onInverseSurface,
  inversePrimary: AppColors.inversePrimary,
  shadow: AppColors.shadow,
  scrim: AppColors.scrim,
);

final ColorScheme householderColorScheme = studentColorScheme.copyWith(
  primary: AppColors.householderPrimary,
  surfaceTint: AppColors.householderPrimary,
);

const ColorScheme studentDarkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: AppColors.studentPrimaryDark,
  onPrimary: AppColors.onPrimaryDark,
  primaryContainer: AppColors.primaryContainerDark,
  onPrimaryContainer: AppColors.onPrimaryContainerDark,
  secondary: AppColors.secondaryDark,
  onSecondary: AppColors.onSecondaryDark,
  secondaryContainer: AppColors.secondaryContainerDark,
  onSecondaryContainer: AppColors.onSecondaryContainerDark,
  tertiary: AppColors.tertiaryDark,
  onTertiary: AppColors.onTertiaryDark,
  tertiaryContainer: AppColors.tertiaryContainerDark,
  onTertiaryContainer: AppColors.onTertiaryContainerDark,
  error: AppColors.errorDark,
  onError: AppColors.onErrorDark,
  errorContainer: AppColors.errorContainerDark,
  onErrorContainer: AppColors.onErrorContainerDark,
  surface: AppColors.surfaceDark,
  onSurface: AppColors.onSurfaceDark,
  onSurfaceVariant: AppColors.onSurfaceVariantDark,
  surfaceContainerLowest: AppColors.surfaceContainerLowestDark,
  surfaceContainerLow: AppColors.surfaceContainerLowDark,
  surfaceContainer: AppColors.surfaceContainerDark,
  surfaceContainerHigh: AppColors.surfaceContainerHighDark,
  surfaceContainerHighest: AppColors.surfaceContainerHighestDark,
  surfaceDim: AppColors.surfaceDimDark,
  surfaceBright: AppColors.surfaceBrightDark,
  surfaceTint: AppColors.studentPrimaryDark,
  outline: AppColors.outlineDark,
  outlineVariant: AppColors.outlineVariantDark,
  inverseSurface: AppColors.inverseSurfaceDark,
  onInverseSurface: AppColors.onInverseSurfaceDark,
  inversePrimary: AppColors.inversePrimaryDark,
  shadow: AppColors.shadow,
  scrim: AppColors.scrim,
);

final ColorScheme householderDarkColorScheme = studentDarkColorScheme.copyWith(
  primary: AppColors.householderPrimaryDark,
  surfaceTint: AppColors.householderPrimaryDark,
);
